name: Debug Nuitka Binaries

on:
  workflow_dispatch:

jobs:
  debug-binaries:
    name: Debug Nuitka binaries (manual)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies from pyproject.toml
        run: pip install .

      - name: Build Executable with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: portablesource_main.py
        # Nuitka-Action автоматически подхватит nuitka-project: опции из pyproject.toml или .nuitkaproject

      - name: Archive binary
        run: |
          cd build
          zip -r ../portablesource-${{ runner.os }}.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: portablesource-${{ runner.os }}
          path: portablesource-${{ runner.os }}.zip 